export const MAXIMUM_QUANTITY = 1_000;
export const MAXIMUM_UNIT_PRICE = 100_000_000;

export const MINIMUM_PROMOTION_IMAGE_WIDTH = 400;
export const MINIMUM_PROMOTION_IMAGE_HEIGHT = 400;

export const MAXIMUM_RESOLUTION_WIDTH = 10_000;
export const MAXIMUM_RESOLUTION_HEIGHT = 10_000;

export const MAXIMUM_QUANTITY_PER_PRODUCT = 10;

export const ROLE_GUEST = "GUEST";
export const ROLE_USER = "USER";
export const ROLE_ADMIN = "ADMIN";

export const REFRESH_TOKENS_TIMESPAN = 10 * 60 * 1000;

export const NUMBER_OF_DELIVERY_DAYS = 3;
export const DELIVERY_FEE = 45_000;